name: Continous Integration

on: 
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with: 
                fetch-depth: 0
            - name: Use Nodej.js
              uses: actions/setup-node@v2
              with:
                node-version: '22.2.0'

            - name: Install dependencies
              run: npm install
