name: Build And Deploy To Digital Ocean
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.2.0'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          ssh -v -o StrictHostKeyChecking=no root@206.189.141.124 'echo SSH connection successful'
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" --delete .next package.json package-lock.json next.config.js root@206.189.141.124:/root/next-CICD/
          ssh -o StrictHostKeyChecking=no root@206.189.141.124 '
            cd /root/next-CICD &&
            npm ci --only=production &&
            pm2 restart site
          '
