name: Build And Deploy To Digital Ocean
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.2.0'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Create known_hosts file
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
      - name: Debug SSH
        run: |
          ssh -v -i ~/.ssh/id_rsa root@206.189.141.124 'echo SSH connection successful'
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          eval $(ssh-agent -s)
          echo "$SSH_PASSPHRASE" | ssh-add ~/.ssh/id_rsa
          ssh -v -o StrictHostKeyChecking=no root@206.189.141.124 'echo SSH connection successful'
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" --delete .next package.json package-lock.json next.config.js root@206.189.141.124:/root/next-CICD/
          ssh -o StrictHostKeyChecking=no root@206.189.141.124 '
            cd /root/next-CICD &&
            npm ci --only=production &&
            pm2 restart site
          '
